// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOmEZ2KtUTGy854dNuSpZbvYg6S7trFO4',
    appId: '1:638419827875:android:d481e143f6f1255345d316',
    messagingSenderId: '638419827875',
    projectId: 'event-app-b47a5',
    storageBucket: 'event-app-b47a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-yiWEF8npCdWorCwJ2WBrKBsuH7pBMdo',
    appId: '1:638419827875:ios:967922be5cfe84b645d316',
    messagingSenderId: '638419827875',
    projectId: 'event-app-b47a5',
    storageBucket: 'event-app-b47a5.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxctVeULOgdYaZtvMS6ej_JDRSlcc2zdw',
    appId: '1:638419827875:web:60fb727f4ff01d9345d316',
    messagingSenderId: '638419827875',
    projectId: 'event-app-b47a5',
    authDomain: 'event-app-b47a5.firebaseapp.com',
    storageBucket: 'event-app-b47a5.firebasestorage.app',
    measurementId: 'G-HRVLW8X2QY',
  );

}